// Mocks generated by Mockito 5.1.0 from annotations
// in flutter_application_1/test/view_models/apply_view_model_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;
import 'dart:io' as _i5;

import 'package:flutter_application_1/configs/firebase_helper.dart' as _i8;
import 'package:flutter_application_1/models/background_info_model.dart' as _i7;
import 'package:flutter_application_1/models/payment_info_model.dart' as _i6;
import 'package:flutter_application_1/models/user_model.dart' as _i4;
import 'package:flutter_application_1/repositories/user_repo.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i2.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.User?> getUser(String? uid) =>
      (super.noSuchMethod(Invocation.method(#getUser, [uid]),
          returnValue: Future<_i4.User?>.value()) as _i3.Future<_i4.User?>);
  @override
  _i3.Future<bool> registerUser(_i4.User? user) =>
      (super.noSuchMethod(Invocation.method(#registerUser, [user]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  _i3.Future<bool> uploadIdentification(_i5.File? file, String? uid) =>
      (super.noSuchMethod(Invocation.method(#uploadIdentification, [file, uid]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  _i3.Future<bool> uploadBankStatement(_i5.File? file, String? uid) =>
      (super.noSuchMethod(Invocation.method(#uploadBankStatement, [file, uid]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  _i3.Future<bool> uploadProofOfAddress(_i5.File? file, String? uid) =>
      (super.noSuchMethod(Invocation.method(#uploadProofOfAddress, [file, uid]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  _i3.Future<bool> addPaymentInfo(_i6.PaymentInfo? paymentInfo, String? uid) =>
      (super.noSuchMethod(
          Invocation.method(#addPaymentInfo, [paymentInfo, uid]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  _i3.Future<bool> addBackgroundInfo(
          _i7.BackgroundInformation? backgroundInformation, String? uid) =>
      (super.noSuchMethod(
          Invocation.method(#addBackgroundInfo, [backgroundInformation, uid]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
}

/// A class which mocks [FirebaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseHelper extends _i1.Mock implements _i8.FirebaseHelper {
  MockFirebaseHelper() {
    _i1.throwOnMissingStub(this);
  }
}
