// Mocks generated by Mockito 5.1.0 from annotations
// in flutter_application_1/test/view_models/view_models_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;
import 'dart:io' as _i5;

import 'package:flutter_application_1/configs/firebase_helper.dart' as _i8;
import 'package:flutter_application_1/models/background_info_model.dart' as _i7;
import 'package:flutter_application_1/models/loan_request_model.dart' as _i10;
import 'package:flutter_application_1/models/notification_model.dart' as _i12;
import 'package:flutter_application_1/models/payment_info_model.dart' as _i6;
import 'package:flutter_application_1/models/user_model.dart' as _i4;
import 'package:flutter_application_1/repositories/loan_request_repo.dart'
    as _i9;
import 'package:flutter_application_1/repositories/notification_repo.dart'
    as _i11;
import 'package:flutter_application_1/repositories/user_repo.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i2.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.User?> getUser(String? uid) =>
      (super.noSuchMethod(Invocation.method(#getUser, [uid]),
          returnValue: Future<_i4.User?>.value()) as _i3.Future<_i4.User?>);
  @override
  _i3.Future<bool> registerUser(_i4.User? user) =>
      (super.noSuchMethod(Invocation.method(#registerUser, [user]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  _i3.Future<bool> uploadIdentification(_i5.File? file, String? uid) =>
      (super.noSuchMethod(Invocation.method(#uploadIdentification, [file, uid]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  _i3.Future<bool> uploadBankStatement(_i5.File? file, String? uid) =>
      (super.noSuchMethod(Invocation.method(#uploadBankStatement, [file, uid]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  _i3.Future<bool> uploadProofOfAddress(_i5.File? file, String? uid) =>
      (super.noSuchMethod(Invocation.method(#uploadProofOfAddress, [file, uid]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  _i3.Future<bool> addPaymentInfo(_i6.PaymentInfo? paymentInfo, String? uid) =>
      (super.noSuchMethod(
          Invocation.method(#addPaymentInfo, [paymentInfo, uid]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  _i3.Future<bool> addBackgroundInfo(
          _i7.BackgroundInformation? backgroundInformation, String? uid) =>
      (super.noSuchMethod(
          Invocation.method(#addBackgroundInfo, [backgroundInformation, uid]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
}

/// A class which mocks [FirebaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseHelper extends _i1.Mock implements _i8.FirebaseHelper {
  MockFirebaseHelper() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [LoanRequestRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoanRequestRepository extends _i1.Mock
    implements _i9.LoanRequestRepository {
  MockLoanRequestRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> createLoanRequest(_i10.LoanRequest? loanRequest) =>
      (super.noSuchMethod(Invocation.method(#createLoanRequest, [loanRequest]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  _i3.Future<_i10.LoanRequest?> getUserLoan(String? uid) =>
      (super.noSuchMethod(Invocation.method(#getUserLoan, [uid]),
              returnValue: Future<_i10.LoanRequest?>.value())
          as _i3.Future<_i10.LoanRequest?>);
}

/// A class which mocks [NotificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationRepository extends _i1.Mock
    implements _i11.NotificationRepository {
  MockNotificationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i12.Notification>?> getNotifications(String? uid) =>
      (super.noSuchMethod(Invocation.method(#getNotifications, [uid]),
              returnValue: Future<List<_i12.Notification>?>.value())
          as _i3.Future<List<_i12.Notification>?>);
}
